# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('manufacturer', models.CharField(max_length=150)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('regno', models.CharField(max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
    ]
