# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20180514_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Car'),
        ),
    ]
